#define TEMPERATURE_GENERATE_THRESHOLD 50
#define AVAILABILITY_GENERATE_THRESHOLD 90
// #define DATA_SEND_THRESHOLD 100
#define MINIMUM_DATA_SEND_COUNT 40
#define MAXIMUM_WAIT_TO_SEND 30
#define TOGGLE_INTERVAL 10
#define MAX_STRING_LENGTH 1000